#pragma once
// Generated by tools/generate_catalogue.py from catalogue/*.yaml (the tile catalogue, app 0.4.32); do not edit.
// The entity types a screen draws, and Home Assistant's feature bits of each by the names its source gives them
// (catalogue/_ha.json, read from Home Assistant core by tools/read_ha_source.py), so no firmware code counts bits by hand.
#include <cstdint>

namespace tile_catalogue {

// Every type a tile can show, the screen's own cards (screen.*) included.
inline constexpr const char *DOMAINS[] = {"alarm_control_panel", "automation", "binary_sensor", "button", "camera", "climate", "cover", "fan", "image", "input_boolean", "input_button", "input_number", "input_select", "light", "lock", "media_player", "number", "person", "remote", "scene", "screen", "script", "select", "sensor", "sun", "switch", "timer", "vacuum", "weather"};

namespace alarm_control_panel {
inline constexpr uint32_t ARM_AWAY = 2;
inline constexpr uint32_t ARM_CUSTOM_BYPASS = 16;
inline constexpr uint32_t ARM_HOME = 1;
inline constexpr uint32_t ARM_NIGHT = 4;
inline constexpr uint32_t ARM_VACATION = 32;
inline constexpr uint32_t TRIGGER = 8;
}  // namespace alarm_control_panel
namespace camera {
inline constexpr uint32_t ON_OFF = 1;
inline constexpr uint32_t STREAM = 2;
}  // namespace camera
namespace climate {
inline constexpr uint32_t FAN_MODE = 8;
inline constexpr uint32_t PRESET_MODE = 16;
inline constexpr uint32_t SWING_HORIZONTAL_MODE = 512;
inline constexpr uint32_t SWING_MODE = 32;
inline constexpr uint32_t TARGET_HUMIDITY = 4;
inline constexpr uint32_t TARGET_TEMPERATURE = 1;
inline constexpr uint32_t TARGET_TEMPERATURE_RANGE = 2;
inline constexpr uint32_t TURN_OFF = 128;
inline constexpr uint32_t TURN_ON = 256;
}  // namespace climate
namespace cover {
inline constexpr uint32_t CLOSE = 2;
inline constexpr uint32_t CLOSE_TILT = 32;
inline constexpr uint32_t OPEN = 1;
inline constexpr uint32_t OPEN_TILT = 16;
inline constexpr uint32_t SET_POSITION = 4;
inline constexpr uint32_t SET_TILT_POSITION = 128;
inline constexpr uint32_t SPEED = 256;
inline constexpr uint32_t STOP = 8;
inline constexpr uint32_t STOP_TILT = 64;
}  // namespace cover
namespace fan {
inline constexpr uint32_t DIRECTION = 4;
inline constexpr uint32_t OSCILLATE = 2;
inline constexpr uint32_t PRESET_MODE = 8;
inline constexpr uint32_t SET_SPEED = 1;
inline constexpr uint32_t TURN_OFF = 16;
inline constexpr uint32_t TURN_ON = 32;
}  // namespace fan
namespace light {
inline constexpr uint32_t EFFECT = 4;
inline constexpr uint32_t FLASH = 8;
inline constexpr uint32_t TRANSITION = 32;
}  // namespace light
namespace lock {
inline constexpr uint32_t OPEN = 1;
}  // namespace lock
namespace media_player {
inline constexpr uint32_t BROWSE_MEDIA = 131072;
inline constexpr uint32_t CLEAR_PLAYLIST = 8192;
inline constexpr uint32_t GROUPING = 524288;
inline constexpr uint32_t MEDIA_ANNOUNCE = 1048576;
inline constexpr uint32_t MEDIA_ENQUEUE = 2097152;
inline constexpr uint32_t NEXT_TRACK = 32;
inline constexpr uint32_t PAUSE = 1;
inline constexpr uint32_t PLAY = 16384;
inline constexpr uint32_t PLAY_MEDIA = 512;
inline constexpr uint32_t PREVIOUS_TRACK = 16;
inline constexpr uint32_t REPEAT_SET = 262144;
inline constexpr uint32_t SEARCH_MEDIA = 4194304;
inline constexpr uint32_t SEEK = 2;
inline constexpr uint32_t SELECT_SOUND_MODE = 65536;
inline constexpr uint32_t SELECT_SOURCE = 2048;
inline constexpr uint32_t SHUFFLE_SET = 32768;
inline constexpr uint32_t STOP = 4096;
inline constexpr uint32_t TURN_OFF = 256;
inline constexpr uint32_t TURN_ON = 128;
inline constexpr uint32_t VOLUME_MUTE = 8;
inline constexpr uint32_t VOLUME_SET = 4;
inline constexpr uint32_t VOLUME_STEP = 1024;
}  // namespace media_player
namespace remote {
inline constexpr uint32_t ACTIVITY = 4;
inline constexpr uint32_t DELETE_COMMAND = 2;
inline constexpr uint32_t LEARN_COMMAND = 1;
}  // namespace remote
namespace vacuum {
inline constexpr uint32_t CLEAN_AREA = 16384;
inline constexpr uint32_t CLEAN_SPOT = 1024;
inline constexpr uint32_t FAN_SPEED = 32;
inline constexpr uint32_t LOCATE = 512;
inline constexpr uint32_t MAP = 2048;
inline constexpr uint32_t PAUSE = 4;
inline constexpr uint32_t RETURN_HOME = 16;
inline constexpr uint32_t SEND_COMMAND = 256;
inline constexpr uint32_t START = 8192;
inline constexpr uint32_t STATE = 4096;
inline constexpr uint32_t STATUS = 128;
inline constexpr uint32_t STOP = 8;
inline constexpr uint32_t TURN_OFF = 2;
inline constexpr uint32_t TURN_ON = 1;
}  // namespace vacuum
namespace weather {
inline constexpr uint32_t FORECAST_DAILY = 1;
inline constexpr uint32_t FORECAST_HOURLY = 2;
inline constexpr uint32_t FORECAST_TWICE_DAILY = 4;
}  // namespace weather

}  // namespace tile_catalogue
